services:
  dairy-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8088:8080"
    environment:
      - MongoDb__ConnectionString=mongodb+srv://naikamit6773_db_user:F4VdIVZdTg2Myhcw@cluster0.pifrqwv.mongodb.net/?appName=Cluster0
      - MongoDb__DatabaseName=DairyDB
      - ServiceUrls__CommonService=http://host.docker.internal:8091
    extra_hosts:
      - "host.docker.internal:host-gateway"
